### ISSUE TITLE
show number of users in a cohort in parenthesis beside cohort name.

### ISSUE THREAD

**Issue by onword** [moodle-an-hochschulen/moodle-local_profilecohort#34]
Hello, just a small feature proposal.
Under "Cohort Members" (administration -> users -> profile field based cohort membership) the cohort names are displayed as well as a dropdown arrow to the left of them. I.e.:

> Cohort 1
> Cohort 2
> Cohort 3
etc.

I'd like to propose showing the current total number of users in each cohort in parenthesis beside the Cohort Name and dropdown arrow:

> Cohort 1 (27)
> Cohort 2 (31)
> Cohort 3 (14)
etc.

Thank you for this plugin.

**Comment by stdoma** [comment]
It would be great if the function was built into the core.
I have adjusted the code that the function is given.
The request is definitely relevant to several people.

**Comment by abias** [comment]
Hi @onword ,

your proposal makes sense.

In 495c875404c5313539bec582c88bb8172dc04457, I have just slightly improved the cohort members list and have added the number of members:

<img width="1326" alt="grafik" src="https://user-images.githubusercontent.com/1092118/235372450-c574e551-a7fe-48b0-8a17-03061d8341cd.png">

I hope you like it!

Cheers,
Alex
