### ISSUE TITLE
Cohort duplicated when new field added

### ISSUE THREAD

**Issue by sioc** [moodle-an-hochschulen/moodle-local_profilecohort#39]
Hi,

Maybe I do something wrong.

1- I created a single entry template.
{{ department }}

2- Then, I want to add a new value to generate new cohorts. So I add a line to my template choosing LF delimiter (Linux server):
{{ department }}
{{ institution }}

All my department existing cohorts were duplicated. And the old cohorts no longer get synchronized.

**Comment by abias** [comment]
Hi @sioc ,

it seems as if you posted this issue to the wrong Github repo. This plugin does not do anything with templates and does not create any cohorts.

I think you meant to post this issue to https://github.com/catalyst/moodle-local_cohortauto which is a similar Moodle plugin.

Cheers,
Alex

**Comment by sioc** [comment]
Oups, silly me.
