### ISSUE TITLE
No custom profile fields listed in add new rule tab

### ISSUE THREAD

**Issue by smlavoie** [moodle-an-hochschulen/moodle-local_profilecohort#42]
After a not torough update from moodle 3.10 to moodle 3.11.7  (by our supplier), all our cohorts based on a conditional profilefield are empty.

Sysadmin updated this plugin from 3.10 to 3.11, entries are still in local_profilecohort table but all our cohorts (more than 70 with 20k users) are now empty. 

Any clues why conditional customfields are not taken in charge?

Thank for any help you could provide.

**Comment by abias** [comment]
Hi @smlavoie ,

I am sorry, but I do not have an idea why your cohorts which are filled based on conditional profilefields are empty now.
However, this plugin does not officially support conditional profilefields. There is an issue on #46 to investigate this possibility.

Cheers,
Alex
