### ISSUE TITLE
Permissions for custom roles to use this plugin on user creation

### ISSUE THREAD

**Issue by Tansohal** [moodle-an-hochschulen/moodle-local_profilecohort#44]
Hey there, its a really good plugin however, I'm unsure as to how to give my lower-level admin users the ability to see this field on the user profile creation tab. For example Id like a manager/teacher to be able to view the extra user profile field and adjust it accordingly.

Essentially make a way for roles to view the profile category on the user creation/edit page

**Comment by abias** [comment]
Hi @Tansohal ,

I am sorry, but this question is unrelated to this plugin. It is a matter of which role is allowed to edit a particular user's profile and who is allowed to see the particular user profile field.

This first is controlled with the moodle/user:editprofile capability, the second is controlled with the "Who is this field visible to?" on the configuration page of the custom profile field.

If you struggle to get this up and running, please don't hesitate to post this question again in the moodle.org forums.

Cheers,
Alex
