### ISSUE TITLE
get_all_user_name_fields() is deprecated

### ISSUE THREAD

**Issue by pkgh** [moodle-an-hochschulen/moodle-local_profilecohort#45]
Debugger output - Moodle 3.11.8, local_profilecohort v3.11-r2 2021061301

The following showed after setting up a rule and switching to the "Cohort members" tab:

get_all_user_name_fields() is deprecated. Please use the \core_user\fields API instead

    line 3384 of /lib/deprecatedlib.php: call to debugging()
    line 108 of /local/profilecohort/classes/profilecohort.php: call to get_all_user_name_fields()
    line 72 of /local/profilecohort/classes/profilecohort.php: call to local_profilecohort\profilecohort->output_members()
    line 43 of /local/profilecohort/index.php: call to local_profilecohort\profilecohort->output_form()

**Comment by abias** [comment]
Thank you for this hint, @pkgh !

I have replaced the call to the deprecated function with the \core_user\fields API in the 3.11 version.
