### ISSUE TITLE
Server get hanged while updating and upgrading the database

### ISSUE THREAD

**Issue by jasimp** [moodle-an-hochschulen/moodle-local_profilecohort#47]
Hi
I got an issue that while updating the server get hanged while updating the database
I am on moodle 3.10 and i tried to update to the below version
v3.10-r4 (2021010903)

**Comment by abias** [comment]
Hi @jasimp ,

thank you for raising this issue.
It would have been interesting from which plugin version you were updating to v3.10-r4.
v3.10-r4 itself just added some documenation which won't do anything with Moodle during the database upgrade.

Looking further down in the plugin history, there haven't been database upgrade steps for a long time. 
I assume that this plugin is not the one to blame for your upgrade problems.

Cheers,
Alex
