### ISSUE TITLE
cohort field now greyed out in app, used to work; still works on PC

### ISSUE THREAD

**Issue by sherig** [moodle-an-hochschulen/moodle-local_profilecohort#51]
What could make the "other field" we use to determine the cohort to enroll into not an available option to click only in the moodle app?  It's greyed out and you can't choose anything. This renders enrollment on the app unusable as it is a required field.

**Comment by abias** [comment]
Hi @sherig ,

I am sorry but this question is unrelated to this plugin. It is related to the Moodle user registration process. Please ask this question in the moodle.org forums.

Cheers,
Alex
