### ISSUE TITLE
Feature request: optical adjustment of the rule overview

### ISSUE THREAD

**Issue by stdoma** [moodle-an-hochschulen/moodle-local_profilecohort#52]
Hello!
I use the user profile data to set groups for all courses and their semesters: This gives me 250 rules.
With this number of rules, the overview suffers a little.
Moodle: 3.11.13+ / Plugin: v3.11-r4 (2021061303)

It would be good if the individual rules could be distinguished quickly. - I am attaching an example.
An extension to this would be if the associated rules were given the style of one line.
For clarity, a view with page selection would be good, where you can select the number of displayed elements: 25, 50, 75, 100, all

Best regards
Stephan

[raw-scss.txt](https://github.com/moodle-an-hochschulen/moodle-local_profilecohort/files/11002321/raw-scss.txt)

**Comment by stdoma** [comment]
I was a little too hasty in commenting on the associated rules.
The rules are connected visually. - very nice.
The positioning of the elements does not seem quite correct to me. (?)
![Screenshot 2023-03-17 162049](https://user-images.githubusercontent.com/92015860/225947799-3862937f-e538-4471-847f-f36dc4f5a860.png)

**Comment by abias** [comment]
Hi @stdoma ,

in the Moodle 4.0 release of this plugin, the rules page was improved visually and the bug with the broken wrapping of subsequent rules was fixed:

<img width="1157" alt="grafik" src="https://user-images.githubusercontent.com/1092118/235362006-e6406983-1c6f-4c19-a083-375f2f19c81e.png">

I hope that this matches your expectations.

Cheers,
Alex
