### ISSUE TITLE
Bug: the rule overview does not always load with many rules

### ISSUE THREAD

**Issue by stdoma** [moodle-an-hochschulen/moodle-local_profilecohort#53]
Hello!
I use the user profile data to set groups for all courses and their semesters: that makes 250 rules.
The rule overview does not always load and the page remains empty. A reload usually helps.
I haven't noticed any problems with saving changes in the rule overview.
I still have to test how the system reacts when I add more rules.

Moodle: 3.11.13+ / Plugin: v3.11-r4 (2021061303)

Best regards
Stephan

**Comment by abias** [comment]
Hi @stdoma ,

I gave an explanation about the pitfalls with large rule sets in this plugin on https://github.com/moodle-an-hochschulen/moodle-local_profilecohort/issues/22#issuecomment-545752226. The same response should appliy to this issue here as well.

Cheers,
Alex
