### ISSUE TITLE
Feature request: Display of the number of members in the group members overview

### ISSUE THREAD

**Issue by stdoma** [moodle-an-hochschulen/moodle-local_profilecohort#55]
There are two pieces of information that interest me in connection with the plugin:
a) The members of a global group
b) The number of members of a global group

I can see the number of members of a global group in the normal settings of the system.
I can see the members of a global group in the plugin.

It would be nice if I could also see the number of members of a group in the plugin itself: "cohort member"-site, behind the names of the groups
The addition is quickly implemented. - Thanks for the good structure.
This may also be relevant for other people.

**Comment by abias** [comment]
Hi @stdoma ,

your proposal makes sense.

In 495c875404c5313539bec582c88bb8172dc04457, I have just slightly improved the cohort members list and have added the number of members:

<img width="1326" alt="grafik" src="https://user-images.githubusercontent.com/1092118/235372450-c574e551-a7fe-48b0-8a17-03061d8341cd.png">

I hope you like it!

Cheers,
Alex
